### ISSUE TITLE
Failed to build with Gentoo kernel 5.6.0

### ISSUE THREAD

**Issue by Nordicruler** [mtorromeo/r8168#24]
/home/tommy/r8168/src/r8168_n.c: In function ‘rtl8168_proc_init’:
/home/tommy/r8168/src/r8168_n.c:1670:47: error: passing argument 4 of ‘proc_create_data’ from incompatibl>
 1670 |                                               &rtl8168_proc_fops, f->show)) {
      |                                               ^~~~~~~~~~~~~~~~~~
      |                                               |
      |                                               const struct file_operations *
In file included from /home/tommy/r8168/src/r8168_n.c:92:
./include/linux/proc_fs.h:59:31: note: expected ‘const struct proc_ops *’ but argument is of type ‘const >
   59 | extern struct proc_dir_entry *proc_create_data(const char *, umode_t,
      |                               ^~~~~~~~~~~~~~~~
/home/tommy/r8168/src/r8168_n.c: At top level:
/home/tommy/r8168/src/r8168_n.c:25821:31: error: initialization of ‘void (*)(struct net_device *, unsigne>
25821 |         .ndo_tx_timeout     = rtl8168_tx_timeout,
      |                               ^~~~~~~~~~~~~~~~~~
/home/tommy/r8168/src/r8168_n.c:25821:31: note: (near initialization for ‘rtl8168_netdev_ops.ndo_tx_timeo>
cc1: some warnings being treated as errors
make[3]: *** [scripts/Makefile.build:268: /home/tommy/r8168/src/r8168_n.o] Error 1
make[2]: *** [Makefile:1685: /home/tommy/r8168/src] Error 2
make[1]: *** [Makefile:140: modules] Error 2
make: *** [Makefile:40: modules] Error 2

**Comment by implementt** [comment]
+1

**Comment by pacho2** [comment]
Maybe this will work:
https://gitlab.manjaro.org/packages/extra/linux56-extramodules/r8168/-/blob/master/kernel56.patch

**Comment by implementt** [comment]
> Maybe this will work:
> https://gitlab.manjaro.org/packages/extra/linux56-extramodules/r8168/-/blob/master/kernel56.patch

trying

**Comment by Nordicruler** [comment]
> Maybe this will work:
> https://gitlab.manjaro.org/packages/extra/linux56-extramodules/r8168/-/blob/master/kernel56.patch

Thanks. It builds and working.

**Comment by implementt** [comment]
> Maybe this will work:
> https://gitlab.manjaro.org/packages/extra/linux56-extramodules/r8168/-/blob/master/kernel56.patch
working.thanks.

**Comment by ohquait** [comment]
this work and **is needed also** on new version **8.048.02**
[https://gitlab.manjaro.org/packages/extra/linux56-extramodules/r8168/-/blob/master/kernel56.patch](url)

can close

**Comment by poseidon-j** [comment]
ssl error

Check old driver and unload it.
rmmod r8168
Build the module and install
At main.c:160:
- SSL error:02001002:system library:fopen:No such file or directory: ../crypto/bio/bss_file.c:69
- SSL error:2006D080:BIO routines:BIO_new_file:no such file: ../crypto/bio/bss_file.c:76
sign-file: certs/signing_key.pem: No such file or directory
Warning: modules_install: missing 'System.map' file. Skipping depmod.
DEPMOD 5.4.0-37-generic
load module r8168
Updating initramfs. Please wait.
update-initramfs: Generating /boot/initrd.img-5.4.0-37-generic
Completed.

**Comment by thimslugga** [comment]
8.048.03 was released on 05-25-2020 and should support 5.6
