### ISSUE TITLE
Compilation error on Linux 5.2.17 (error: implicit declaration of function ‘synchronize_sched’; did you mean ‘synchronize_net’)

### ISSUE THREAD

**Issue by Drag0nFly** [mtorromeo/r8168#21]
The (presumably latest) r8168 version fails on a recent 5.2.x kernel when compiling r8168_n.c with the following message –

```
make -C src/ modules
make: Entering directory '/root/realtek/r8168-8.046.00/src'
make -C /lib/modules/5.2.17.a-1-hardened-arch-atom/build SUBDIRS=/root/realtek/r8168-8.046.00/src modules
make[1]: Entering directory '/home/martin/abs/core/linux-hardened/newer/src/linux-5.2.17'
Makefile:213: ================= WARNING ================
Makefile:214: 'SUBDIRS' will be removed after Linux 5.3
Makefile:215: Please use 'M=' or 'KBUILD_EXTMOD' instead
Makefile:216: ==========================================
  CC [M]  /root/realtek/r8168-8.046.00/src/r8168_n.o
/root/realtek/r8168-8.046.00/src/r8168_n.c: In function ‘rtl8168_down’:
/root/realtek/r8168-8.046.00/src/r8168_n.c:28376:9: error: implicit declaration of function ‘synchronize_sched’; did you mean ‘synchronize_net’? [-Werror=implicit-function-declaration]
28376 |         synchronize_sched();  /* FIXME: should this be synchronize_irq()? */
      |         ^~~~~~~~~~~~~~~~~
      |         synchronize_net
cc1: some warnings being treated as errors
make[2]: *** [scripts/Makefile.build:279: /root/realtek/r8168-8.046.00/src/r8168_n.o] Error 1
make[1]: *** [Makefile:1597: _module_/root/realtek/r8168-8.046.00/src] Error 2
make[1]: Leaving directory '/home/martin/abs/core/linux-hardened/newer/src/linux-5.2.17'
make: *** [Makefile:104: modules] Error 2
make: Leaving directory '/root/realtek/r8168-8.046.00/src'
```

Another error occurs when replacing the call to the synchronize_sched() function with synchronize_irc() (as suggested by the code comment) –

```
make -C src/ modules
make: Entering directory '/root/realtek/r8168-8.046.00/src'
make -C /lib/modules/5.2.17.a-1-hardened-arch-atom/build SUBDIRS=/root/realtek/r8168-8.046.00/src modules
make[1]: Entering directory '/home/martin/abs/core/linux-hardened/newer/src/linux-5.2.17'
Makefile:213: ================= WARNING ================
Makefile:214: 'SUBDIRS' will be removed after Linux 5.3
Makefile:215: Please use 'M=' or 'KBUILD_EXTMOD' instead
Makefile:216: ==========================================
  CC [M]  /root/realtek/r8168-8.046.00/src/r8168_n.o
/root/realtek/r8168-8.046.00/src/r8168_n.c: In function ‘rtl8168_down’:
/root/realtek/r8168-8.046.00/src/r8168_n.c:28376:9: error: too few arguments to function ‘synchronize_irq’
28376 |         synchronize_irq();  /* FIXME: should this be synchronize_irq()? */
      |         ^~~~~~~~~~~~~~~
In file included from ./include/linux/interrupt.h:11,
                 from ./include/linux/pci.h:32,
                 from /root/realtek/r8168-8.046.00/src/r8168_n.c:40:
./include/linux/hardirq.h:12:13: note: declared here
   12 | extern void synchronize_irq(unsigned int irq);
      |             ^~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:279: /root/realtek/r8168-8.046.00/src/r8168_n.o] Error 1
make[1]: *** [Makefile:1597: _module_/root/realtek/r8168-8.046.00/src] Error 2
make[1]: Leaving directory '/home/martin/abs/core/linux-hardened/newer/src/linux-5.2.17'
make: *** [Makefile:104: modules] Error 2
make: Leaving directory '/root/realtek/r8168-8.046.00/src'
```

**Comment by Drag0nFly** [comment]
Thoughts anyone?

**Comment by Drag0nFly** [comment]
I visited the link to Realtek's pages (thinking it was dead as all the others were) and downloaded the most recent r8168-8.047.04 version and it *actually* does* compile on 5.2.17.

make -C src/ clean
make[1]: Entering directory '/root/realtek/r8168-8.047.04/src'
make -C /lib/modules/5.2.17.a-1-hardened-arch-atom/build M=/root/realtek/r8168-8.047.04/src clean
make[2]: Entering directory '/home/martin/abs/core/linux-hardened/src/linux-5.2.17'
make[2]: Leaving directory '/home/martin/abs/core/linux-hardened/src/linux-5.2.17'
make[1]: Leaving directory '/root/realtek/r8168-8.047.04/src'
make -C src/ modules
make[1]: Entering directory '/root/realtek/r8168-8.047.04/src'
make -C /lib/modules/5.2.17.a-1-hardened-arch-atom/build M=/root/realtek/r8168-8.047.04/src modules
make[2]: Entering directory '/home/martin/abs/core/linux-hardened/src/linux-5.2.17'
  CC [M]  /root/realtek/r8168-8.047.04/src/r8168_n.o
  CC [M]  /root/realtek/r8168-8.047.04/src/r8168_asf.o
  CC [M]  /root/realtek/r8168-8.047.04/src/rtl_eeprom.o
  CC [M]  /root/realtek/r8168-8.047.04/src/rtltool.o
  LD [M]  /root/realtek/r8168-8.047.04/src/r8168.o
  Building modules, stage 2.
  MODPOST 1 modules
WARNING: modpost: Found 5 writable function pointers.
To see full details build your kernel with:
'make CONFIG_DEBUG_WRITABLE_FUNCTION_POINTERS_VERBOSE=y'
  CC      /root/realtek/r8168-8.047.04/src/r8168.mod.o
  LD [M]  /root/realtek/r8168-8.047.04/src/r8168.ko
make[2]: Leaving directory '/home/martin/abs/core/linux-hardened/src/linux-5.2.17'
make[1]: Leaving directory '/root/realtek/r8168-8.047.04/src'
make -C src/ install
make[1]: Entering directory '/root/realtek/r8168-8.047.04/src'
make -C /lib/modules/5.2.17.a-1-hardened-arch-atom/build M=/root/realtek/r8168-8.047.04/src INSTALL_MOD_DIR=kernel/drivers/net/ethernet/realtek modules_install
make[2]: Entering directory '/home/martin/abs/core/linux-hardened/src/linux-5.2.17'
  INSTALL /root/realtek/r8168-8.047.04/src/r8168.ko
  DEPMOD  5.2.17.a-1-hardened-arch-atom
make[2]: Leaving directory '/home/martin/abs/core/linux-hardened/src/linux-5.2.17'
make[1]: Leaving directory '/root/realtek/r8168-8.047.04/src'

it also detected the NIC after the r8169 module was rmmod-ed, and r8168 inserted. Let's see how it behaves!

**Comment by Drag0nFly** [comment]
And btw., the reason I am trying the r8168 driver is due to the 'transmit queue 0 timed out' errors, which only occurs with one of the two on-board RTL8168d/8111d interfaces (the lowest mac addr)

However, lately the system has also lost eth1 when running for a time - link appears to be ok on the kernel side, but does not allow traffic. No logs or anything reported.

Actually, dmesg *does not* output anything else (r8169 or otherwise) after this error occurs. It is pretty weird, so I am mentioning it here in case others have experienced something similar.

**Comment by mtorromeo** [comment]
You were trying to compile r8168-8.046.00 while this repo was already at 8.047.04 son I don't see the issue.
