### ISSUE TITLE
Version 8.042 - Build error for 2.6.32 kernel

### ISSUE THREAD

**Issue by sergey-dryabzhinsky** [mtorromeo/r8168#6]
Build for Proxmox 3.4 with kernel 2.6.32-46-pve:
```
root@proxmox:~/build/r8168-8.042/src# make all KERNELDIR=/lib/modules/2.6.32-46-pve/build
find: `/lib/modules/2.6.32-39-pve/kernel/drivers/net/ethernet': No such file or directory
make -C /lib/modules/2.6.32-46-pve/build SUBDIRS=/root/build/r8168-8.042/src clean
expr: syntax error
make[1]: Entering directory `/usr/src/linux-headers-2.6.32-46-pve'
make[1]: Leaving directory `/usr/src/linux-headers-2.6.32-46-pve'
make -C /lib/modules/2.6.32-46-pve/build SUBDIRS=/root/build/r8168-8.042/src modules
expr: syntax error
make[1]: Entering directory `/usr/src/linux-headers-2.6.32-46-pve'
  CC [M]  /root/build/r8168-8.042/src/r8168_n.o
/root/build/r8168-8.042/src/r8168_n.c: In function ‘rtl8168_init_one’:
/root/build/r8168-8.042/src/r8168_n.c:22792:20: error: ‘struct net_device’ has no member named ‘hw_features’
/root/build/r8168-8.042/src/r8168_n.c:22793:20: error: ‘struct net_device’ has no member named ‘hw_features’
/root/build/r8168-8.042/src/r8168_n.c:22796:28: error: ‘struct net_device’ has no member named ‘hw_features’
/root/build/r8168-8.042/src/r8168_n.c:22803:28: error: ‘struct net_device’ has no member named ‘hw_features’
/root/build/r8168-8.042/src/r8168_n.c: In function ‘rtl8168_hw_config’:
/root/build/r8168-8.042/src/r8168_n.c:23221:24: error: ‘struct net_device’ has no member named ‘hw_features’
make[2]: *** [/root/build/r8168-8.042/src/r8168_n.o] Error 1
make[1]: *** [_module_/root/build/r8168-8.042/src] Error 2
make[1]: Leaving directory `/usr/src/linux-headers-2.6.32-46-pve'
make: *** [modules] Error 2
```

Version 8.041 builds fine.

**Comment by mtorromeo** [comment]
Sorry but this repository is just a mirror of realtek's code.
I guess this version of the module does not support linux 2.6.32.

**Comment by sergey-dryabzhinsky** [comment]
Just for reference - kernel version must be >= 2.6.39 / 3.0 now.

**Comment by gotnix** [comment]
I use r8168-8.041.00 on CentOS 6.5 with Kernel 2.6.32-431.el6.x86_64, It's worked.

**Comment by sergey-dryabzhinsky** [comment]
Just to mention - 8.044 working fine with 2.6.32 kernel in Proxmox 3.4.
